version: GraphicsMagick.NET-{branch}.{build}

os: Windows Server 2012 R2

clone_folder: C:\GraphicsMagick.NET
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:
  - C:\GraphicsMagick.NET.libs -> GraphicsMagick\Source\CompileDate.txt

environment:

  matrix:
    - gm_platform: "x86"
      gm_name:     "net40-Q8"
    - gm_platform: "x86"
      gm_name:     "net20-Q8"
    - gm_platform: "x86"
      gm_name:     "net40-Q16"
    - gm_platform: "x86"
      gm_name:     "net20-Q16"

    - gm_platform: "x64"
      gm_name:     "net40-Q8"
    - gm_platform: "x64"
      gm_name:     "net20-Q8"
    - gm_platform: "x64"
      gm_name:     "net40-Q16"
    - gm_platform: "x64"
      gm_name:     "net20-Q16"

install:
  - cd Tools\AppVeyor
  - Install.cmd

build_script:
  - Build.cmd %gm_platform% %gm_name%

test_script:
  - Test.cmd